apiVersion: v1
kind: Namespace
metadata:
  name: hello-kube

---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hello-kube-app
  name: hello-kube
  namespace: hello-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-kube-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-kube-app
    spec:
      containers:
      - image: public.ecr.aws/n3k8l3x8/hello-kube:latest
        name: hello-world
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-kube
  namespace: hello-kube
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-1:814379630282:certificate/9d2e3205-1bb1-4d91-8e92-afbaf3dea167
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: hello-kube-app
  ports:
    - name: https
      port: 443
      targetPort: 8080
